version: '3.2'

services:
    api:
        build: .
        image: codee-runner-piston
        container_name: codee-runner-piston
        restart: always
        ports:
            - 2000:2000
        tmpfs:
            - /piston/jobs:exec
            - /tmp:exec
