name: Build, Deploy

on:
  push:
    branches:
      - master
      - develop

jobs:
  Main:
    runs-on: ubuntu-20.04

    steps:
      - name: 'Setup: Git checkout'
        uses: actions/checkout@v2

      - name: 'Setup: Extract branch name'
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: 'Setup: Set env'
        uses: kanga333/variable-mapper@v0.2.0
        with:
          key: '${{ steps.extract_branch.outputs.branch }}'
          map: |
            {
              "master": {
                "SECRET_NAME_GCP_SERVICE_ACCOUNT_KEY": "PROD_GCP_SERVICE_ACCOUNT_KEY",
                "GCP_PROJECT_ID": "codee-club"
              },
              "develop": {
                "SECRET_NAME_GCP_SERVICE_ACCOUNT_KEY": "DEV_GCP_SERVICE_ACCOUNT_KEY",
                "GCP_PROJECT_ID": "codee-club-dev"
              },
              "*": {
                "GCP_PROJECT_ID": "codee-club-emu"
              }
            }

      - name: 'Setup: Google Cloud SDK'
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets[env.SECRET_NAME_GCP_SERVICE_ACCOUNT_KEY] }}
          export_default_credentials: true

      - name: "Setup: Log in to GitHub Docker Registry"
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets[env.SECRET_NAME_GCP_SERVICE_ACCOUNT_KEY] }}

      - name: "Build: Build image and push to GCR"
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            gcr.io/${{ env.GCP_PROJECT_ID }}/runner-piston:latest
            gcr.io/${{ env.GCP_PROJECT_ID }}/runner-piston:${{ github.run_number }}

      - name: 'Deploy: Wait at turnstile'
        uses: softprops/turnstyle@v1
        with:
          abort-after-seconds: 300
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Deploy: Push to Cloud Run'
        uses: google-github-actions/deploy-cloudrun@main
        with:
          service: runner-piston
          image: gcr.io/${{ env.GCP_PROJECT_ID }}/runner-piston:${{ github.run_number }}
